main: com.swiftpenguin.staffactivity.StaffActivity
name: staffactivity
version: 1.1
author: Cobwebster

commands:
  staffcheck:
     description: staffChecker
     usuage: /<command>

permissions:
    staffcheck.use:
        description: Allows usage
        default: op
    staff.log:
        description: Allows logging
        default: op
